
CREATE DATABASE PIAPW1;

USE PIAPW1;

CREATE TABLE TB_USUARIO(
IDUsuario INT PRIMARY KEY AUTO_INCREMENT,
Correo VARCHAR(20) UNIQUE,
Usuario VARCHAR(20) UNIQUE,
Foto VARCHAR(255),
FechaNac DATE,
Edad INT,
Nombre VARCHAR(20),
SNombre VARCHAR(20),
ApPaterno VARCHAR(20),
ApMaterno VARCHAR(20),
Pass VARCHAR(16),
FechaAlta DATETIME DEFAULT now()
);

CREATE TABLE TB_CATEGORIA(
IDCategoria INT PRIMARY KEY AUTO_INCREMENT,
Categoria VARCHAR(20)
);

CREATE TABLE TB_PUBLICACION(
IDPublicacion INT PRIMARY KEY AUTO_INCREMENT,
Titulo VARCHAR(50),
Contenido VARCHAR(150),
Imagen VARCHAR(255),
Estatus BIT,
IDUsuario INT,
IDCategoria INT,
FechaAlta DATETIME DEFAULT now(),
FOREIGN KEY (IDUsuario) REFERENCES TB_USUARIO(IDUsuario),
FOREIGN KEY (IDCategoria) REFERENCES TB_CATEGORIA(IDCategoria)
);